"""Vault projections — regenerate the derived views (graph.json + Plan.md) from the graph.

A note's truth lives in the graph (notes + typed edges); the JSON graph and the actionable
`Plan.md` (with its Mermaid diagram) are pure projections of it (SPEC §11 "one source, three
views"). Both the CLI and the GUI call this after a write so the plan stays current — the
"grand plan" materializes as notes are captured.

Safety (writing into a real Obsidian vault): these are *generated* files, regenerated on every
save. If a file named `Plan.md` / `graph.json` already exists and was **not** produced by
grandplan (e.g. the user's own hand-written plan), it is **never overwritten** — grandplan diverts
its output to a `<stem>.grandplan.<ext>` sibling and logs a warning, so no user data is clobbered.
"""

from __future__ import annotations

import json
import logging
from collections.abc import Callable
from pathlib import Path

from grandplan.core.graph import export_graph
from grandplan.core.planner import write_plan
from grandplan.core.ports import NoteRepository

logger = logging.getLogger(__name__)

# A marker line render_plan() always emits, used to recognise a grandplan-generated Plan.md.
_PLAN_MARKER = "Generated projection of the knowledge graph"


def write_projections(repo: NoteRepository, vault_dir: Path) -> tuple[Path, Path]:
    """Write `graph.json` + `Plan.md` into `vault_dir`; return their paths. Idempotent.

    Foreign same-named files are preserved (output is diverted to a `.grandplan` sibling).
    """
    vault_dir.mkdir(parents=True, exist_ok=True)
    graph_path = export_graph(repo, _safe_target(vault_dir / "graph.json", _is_grandplan_graph))
    plan_path = write_plan(repo, _safe_target(vault_dir / "Plan.md", _is_grandplan_plan))
    return graph_path, plan_path


def _safe_target(path: Path, is_ours: Callable[[Path], bool]) -> Path:
    """The path to write — diverted to a `.grandplan` sibling if a foreign file occupies it.

    Recurses so a chain of foreign files (e.g. both `Plan.md` and `Plan.grandplan.md` are the
    user's) is never clobbered; it terminates at the first free or grandplan-owned slot.
    """
    if not path.exists() or is_ours(path):
        return path
    diverted = path.with_name(f"{path.stem}.grandplan{path.suffix}")
    logger.warning(
        "%s exists and was not generated by grandplan; writing %s instead so your file is kept",
        path.name,
        diverted.name,
    )
    return _safe_target(diverted, is_ours)


def _is_grandplan_plan(path: Path) -> bool:
    try:
        head = path.read_text(encoding="utf-8")[:2048]
    except OSError:
        return False
    return _PLAN_MARKER in head


def _is_grandplan_graph(path: Path) -> bool:
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return False
    # The `_grandplan` sentinel distinguishes our export from any other tool's {nodes,edges} JSON
    # (D3/networkx/Cytoscape all use that shape), so we never overwrite a foreign graph export.
    return isinstance(data, dict) and data.get("_grandplan") is True
